TOPLEVEL_LANG = verilog

VERILOG_SOURCES = ./coin_acceptor_rtl.v
TOPLEVEL = coin_acceptor_rtl
MODULE = test_coin_acceptor

SIM = icarus
WAVES = 1

COCOTB_REDUCED_LOG_FMT = 1

include $(shell cocotb-config --makefiles)/Makefile.sim

